site_name: Portfolio
site_author: Krzysztof Kleszcz
site_description: >-
  Portfolio moich projektÃ³w. 

repo_name: krzysztofkleszcz50/datascience_portfolio
repo_url: https://github.com/krzysztofkleszcz50/datascience_portfolio/tree/master


theme:
  name: material
  palette:
    primary: amber

nav:
- Welcome page ğŸ‘‹: index.md
- Data4Apps ğŸ•µï¸â€â™€ï¸: survey_analysis/index.md
- Data4Play ğŸ’»: data_playground/index.md
- Mini Projects âœ¨: tablo/index.md

